#!/usr/bin/env python3
"""Bake the quote wall into quotes.html as static HTML.

Reads data/quotes-all.json and rewrites everything between the
QUOTE-WALL:START / QUOTE-WALL:END markers in quotes.html. Static cards
mean crawlers (and no-JS readers) see every quote instead of a skeleton
(site review 5a); the page's JS only adds search, facets, and copying.

Run after editing data/quotes-all.json:
    python .github/scripts/generate_quote_wall.py
"""

import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
START = "<!-- QUOTE-WALL:START (generated by generate_quote_wall.py; do not edit by hand) -->"
END = "<!-- QUOTE-WALL:END -->"


def card(idx, q):
    quote = html.escape(q["q"])
    author = html.escape(q["a"])
    book = html.escape(q.get("b") or "")
    footer = f"&mdash; {author}" + (f", <em>{book}</em>" if book else "")
    return (
        f'<article class="kr-quote-card" id="q-{idx}" data-a="{html.escape(q["a"].lower(), quote=True)}">'
        f'<a class="kr-quote-link" href="#q-{idx}" aria-label="Copy link to this quote" '
        f'title="Copy link to this quote">#</a>'
        f"<p>{quote}</p>"
        f"<footer>{footer}</footer>"
        f'<button type="button" class="kr-quote-copy" aria-label="Copy this quote by {html.escape(q["a"], quote=True)}">Copy</button>'
        f'<span class="kr-quote-copied" aria-hidden="true">Copied</span>'
        f"</article>"
    )


def main():
    quotes = json.loads((ROOT / "data" / "quotes-all.json").read_text(encoding="utf-8"))
    body = "\n".join(card(i, q) for i, q in enumerate(quotes))

    page_path = ROOT / "quotes.html"
    page = page_path.read_text(encoding="utf-8")
    if START not in page or END not in page:
        print("markers not found in quotes.html — aborting")
        return 1

    new = re.sub(
        re.escape(START) + r".*?" + re.escape(END),
        START + "\n" + body + "\n" + END,
        page,
        flags=re.S,
    )
    page_path.write_text(new, encoding="utf-8", newline="\n")
    print(f"baked {len(quotes)} quotes into quotes.html")
    return 0


if __name__ == "__main__":
    sys.exit(main())
