#!/usr/bin/env python3
"""Write sitemap.xml from the tracked pages and data/posts.json.

    python .github/scripts/generate_sitemap.py           # write sitemap.xml
    python .github/scripts/generate_sitemap.py --check   # exit 1 if stale

Which pages. Every git-tracked .html page a search engine should index,
by the same rule audit_site.py uses when it checks the sitemap from the
other side: not the search-console verification stub (audit_site's
EXEMPT_PAGES, imported rather than restated), not 404.html, not the
standalone demo files in blog/downloads/, and not any page carrying
`<meta name="robots" content="noindex">` (redirect stubs for renamed
posts, offline.html, privacy.html). Untracked drafts are never listed,
because git ls-files is the list of what Pages serves.

lastmod. A post's comes from its posts.json entry, `updated` when the
entry has one and `date` otherwise: the only date on the site that
records a person deciding the content changed. Top-level pages get none.
Their content moves with data files and scripts on a schedule no one
records, and a guessed date is worse than none: a crawler that sees
lastmod change without the page changing learns to ignore the field
for the whole site.

No changefreq or priority. Google ignores both, and in the hand-kept
sitemap they were guesses nobody revisited: every post "yearly" at 0.8
whatever its age, and two pages (map.html, quotes.html) added without
either.

Output is sorted by URL, so the diff when a post is published is one
added line.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
from urllib.parse import quote
from xml.sax.saxutils import escape

sys.path.insert(0, str(Path(__file__).resolve().parent))
import audit_site  # noqa: E402  (shares the page parser and the exemptions)
import sitelib  # noqa: E402

ROOT = audit_site.ROOT
SITE = sitelib.SITE
OUT = ROOT / "sitemap.xml"

# Pages audit_site.py's sitemap block also skips. 404.html is noindex as
# well, so it would fall out on that rule alone; it is named because the
# audit names it, and the two lists should read the same.
NOT_PAGES = {"404.html"}


def noindex(html: str) -> bool:
    """Whether the page asks not to be indexed, read by audit_site's own
    parser so the two scripts cannot disagree about what counts."""
    parser = audit_site.PageParser()
    parser.feed(html)
    return parser.noindex


def indexable(rel: str, html: str) -> bool:
    """True when the page at `rel` belongs in the sitemap.

    The one rule for this question; audit_site.py applies the same
    exemptions when it reports a page missing from the sitemap.
    """
    if rel in audit_site.EXEMPT_PAGES or rel in NOT_PAGES:
        return False
    if not sitelib.is_page(rel):
        return False
    return not noindex(html)


def url_for(rel: str) -> str:
    if rel == "index.html":
        return SITE + "/"
    return SITE + "/" + quote(rel)


def entries() -> list[tuple[str, str | None]]:
    """(loc, lastmod or None) for every indexable page, sorted by loc."""
    lastmod = {p["url"]: (p.get("updated") or p["date"]) for p in sitelib.load_posts()}
    out = []
    for page in sitelib.tracked("*.html"):
        rel = page.relative_to(ROOT).as_posix()
        if indexable(rel, page.read_text(encoding="utf-8", errors="replace")):
            out.append((url_for(rel), lastmod.get(rel)))
    return sorted(out)


def render(rows: list[tuple[str, str | None]]) -> str:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by .github/scripts/generate_sitemap.py. Do not edit by hand. -->",
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    for loc, mod in rows:
        tail = "<lastmod>%s</lastmod>" % mod if mod else ""
        lines.append("  <url><loc>%s</loc>%s</url>" % (escape(loc), tail))
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def parse(text: str) -> dict[str, str | None]:
    """loc -> lastmod from an existing sitemap, for a readable --check."""
    out = {}
    for block in re.findall(r"<url>(.*?)</url>", text, re.S):
        loc = re.search(r"<loc>\s*(.*?)\s*</loc>", block, re.S)
        mod = re.search(r"<lastmod>\s*(.*?)\s*</lastmod>", block, re.S)
        if loc:
            out[loc.group(1)] = mod.group(1) if mod else None
    return out


def main(argv: list[str] | None = None) -> int:
    ap = sitelib.arg_parser(__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if sitemap.xml differs from a fresh build; write nothing")
    args = ap.parse_args(argv)

    rows = entries()
    text = render(rows)

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current.replace("\r\n", "\n") == text:
            print("sitemap.xml is up to date (%d pages)." % len(rows))
            return 0
        have, want = parse(current), dict(rows)
        print("sitemap.xml is stale:")
        for loc in sorted(set(want) - set(have)):
            print("  missing  " + loc)
        for loc in sorted(set(have) - set(want)):
            print("  extra    " + loc)
        for loc in sorted(set(have) & set(want)):
            if have[loc] != want[loc]:
                print("  lastmod  %s: %s -> %s" % (loc, have[loc], want[loc]))
        if set(have) == set(want) and all(have[k] == want[k] for k in want):
            print("  (same pages and dates; the formatting differs)")
        print("run: python .github/scripts/generate_sitemap.py")
        return 1

    OUT.write_text(text, encoding="utf-8", newline="\n")
    print("Wrote sitemap.xml: %d pages, %d with lastmod."
          % (len(rows), sum(1 for _, m in rows if m)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
