#!/usr/bin/env python3
"""Bake the quote wall into quotes.html as static HTML.

Reads data/quotes-all.json and rewrites everything between the
QUOTE-WALL:START / QUOTE-WALL:END markers in quotes.html. Static cards
mean crawlers (and no-JS readers) see every quote instead of a skeleton,
which is all a script-built wall gave them; the page's JS only adds
search, facets, and copying.

Run after editing data/quotes-all.json:
    python .github/scripts/generate_quote_wall.py
    python .github/scripts/generate_quote_wall.py --check   # exit 1 if quotes.html is stale

--check rebuilds the page in memory and compares it with the file on
disk, line endings normalised: the working copy may be CRLF while the
build writes LF, and that difference is not staleness.
"""

import html
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import sitelib  # noqa: E402

ROOT = sitelib.ROOT
PAGE = ROOT / "quotes.html"
QUOTES = ROOT / "data" / "quotes-all.json"
START = "<!-- QUOTE-WALL:START (generated by generate_quote_wall.py; do not edit by hand) -->"
END = "<!-- QUOTE-WALL:END -->"


def card(idx, q):
    quote = html.escape(q["q"])
    author = html.escape(q["a"])
    book = html.escape(q.get("b") or "")
    footer = f"&mdash; {author}" + (f", <em>{book}</em>" if book else "")
    return (
        f'<article class="kr-quote-card" id="q-{idx}" data-a="{html.escape(q["a"].lower(), quote=True)}">'
        f'<a class="kr-quote-link" href="#q-{idx}" aria-label="Copy link to this quote" '
        f'title="Copy link to this quote">#</a>'
        f"<p>{quote}</p>"
        f"<footer>{footer}</footer>"
        f'<button type="button" class="kr-quote-copy" aria-label="Copy this quote by {html.escape(q["a"], quote=True)}">Copy</button>'
        f'<span class="kr-quote-copied" aria-hidden="true">Copied</span>'
        f"</article>"
    )


def render(page: str, quotes: list) -> str:
    """quotes.html with the wall between the markers rebuilt."""
    body = "\n".join(card(i, q) for i, q in enumerate(quotes))
    return re.sub(
        re.escape(START) + r".*?" + re.escape(END),
        lambda _m: START + "\n" + body + "\n" + END,
        page,
        flags=re.S,
    )


def main(argv=None):
    parser = sitelib.arg_parser(__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if quotes.html differs from a fresh bake; write nothing")
    args = parser.parse_args(argv)

    quotes = json.loads(QUOTES.read_text(encoding="utf-8"))
    with open(PAGE, encoding="utf-8", newline="") as fh:
        raw = fh.read()
    page = raw.replace("\r\n", "\n")
    if START not in page or END not in page:
        print("markers not found in quotes.html, aborting")
        return 1

    new = render(page, quotes)
    if args.check:
        if new != page:
            print("quotes.html is stale: its quote wall does not match data/quotes-all.json.")
            print("run: python .github/scripts/generate_quote_wall.py")
            return 1
        print(f"quotes.html carries all {len(quotes)} quotes, up to date.")
        return 0

    PAGE.write_text(new, encoding="utf-8", newline="\n")
    print(f"baked {len(quotes)} quotes into quotes.html")
    return 0


if __name__ == "__main__":
    sys.exit(main())
