#!/usr/bin/env python3
"""Build style.min.css from style.css.

Root style.css is the editable source: a run of @import lines (the vendor
sheets and the template's css/style.css) followed by the site's own CSS.
This script inlines every imported file (rewriting relative url() paths
to be root-relative and dropping each file's @charset, which is only
valid as the first bytes of a stylesheet), minifies conservatively,
prunes the rules and @keyframes nothing on the site can use (see
css_prune.py for what counts as use), and writes one self-contained
style.min.css: no @import chain, so the browser makes one CSS request
instead of one per import.

Usage:
    python .github/scripts/minify_css.py            # rebuild style.min.css
    python .github/scripts/minify_css.py --check    # exit 1 if style.min.css is stale

Edit style.css (or the imported css/ files), then rerun. Never edit
style.min.css by hand.
"""

import hashlib
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import sitelib  # noqa: E402
from css_prune import (  # noqa: E402
    collect_usage, keyframe_references, prune, prune_keyframes)

ROOT = sitelib.ROOT
SOURCE = ROOT / "style.css"
TARGET = ROOT / "style.min.css"

BANNER = "/*! Generated by .github/scripts/minify_css.py from style.css — do not edit directly. */"

IMPORT_RE = re.compile(r'@import\s+url\(\s*[\'"]?([^\'")]+)[\'"]?\s*\)\s*;')
URL_RE = re.compile(r'url\(\s*([\'"]?)([^\'")]+)\1\s*\)')
COMMENT_RE = re.compile(r'/\*.*?\*/', re.DOTALL)
CHARSET_RE = re.compile(r'@charset\s+(?:"[^"]*"|\'[^\']*\')\s*;', re.IGNORECASE)


def rewrite_urls(css: str, base: Path) -> str:
    """Make relative url() paths root-relative for a file living at `base`."""
    def repl(m):
        quote, target = m.group(1), m.group(2)
        if target.startswith(("data:", "http://", "https://", "/", "#")):
            return m.group(0)
        # keep query/fragment suffixes attached to the path
        path, sep, suffix = re.match(r"([^?#]*)([?#]?)(.*)", target).groups()
        resolved = (base.parent / path).resolve()
        try:
            rel = resolved.relative_to(ROOT).as_posix()
        except ValueError:
            return m.group(0)
        return f"url({quote}{rel}{sep}{suffix}{quote})"
    return URL_RE.sub(repl, css)


STRING_RE = re.compile(r'"(?:[^"\\]|\\.)*"|\'(?:[^\'\\]|\\.)*\'')


def minify(css: str) -> str:
    """Conservative minifier: strips comments and collapses whitespace.

    Quoted strings pass through untouched — attribute selectors like
    [style*="color: rgb(99, 99, 99)"] must keep their exact spacing to
    match runtime style attributes. Also does NOT remove spaces around
    ':' (would merge descendant selectors with pseudo-classes) —
    safety over the last few bytes.
    """
    css = COMMENT_RE.sub("", css)
    out = []
    pos = 0
    for m in STRING_RE.finditer(css):
        out.append((css[pos:m.start()], False))
        out.append((m.group(0), True))
        pos = m.end()
    out.append((css[pos:], False))

    def squeeze(chunk):
        chunk = re.sub(r"\s+", " ", chunk)
        return re.sub(r"\s*([{};,])\s*", r"\1", chunk)

    css = "".join(seg if is_str else squeeze(seg) for seg, is_str in out)
    css = re.sub(r";\}", "}", css)
    return css.strip()


# Icon fonts are subset by .github/scripts/subset_icon_fonts.py; swap each vendor
# @font-face src to the subset files when they exist. Applied to the
# minified text, so quoting/whitespace are predictable.
FONT_SUBSTITUTIONS = [
    ("fonts/fontawesome-subset.woff2",
     re.compile(r"(@font-face\{font-family:\s*'FontAwesome';)[^}]*\}"),
     "src:url(fonts/fontawesome-subset.woff2) format('woff2'),"
     "url(fonts/fontawesome-subset.woff) format('woff');"
     "font-weight:normal;font-style:normal}"),
    ("fonts/themify-subset.woff",
     re.compile(r"(@font-face\{font-family:\s*'themify';)[^}]*\}"),
     "src:url(fonts/themify-subset.woff) format('woff'),"
     "url(fonts/themify-subset.ttf) format('truetype');"
     "font-weight:normal;font-style:normal}"),
    ("css/fonts/ElegantIcons-subset.woff",
     re.compile(r"(@font-face\{font-family:\s*'ElegantIcons';)[^}]*\}"),
     "src:url(css/fonts/ElegantIcons-subset.woff) format('woff'),"
     "url(css/fonts/ElegantIcons-subset.ttf) format('truetype');"
     "font-weight:normal;font-style:normal}"),
]


def fingerprint(css_url: str) -> str:
    """`css_url` with a query naming its bytes. A subset keeps its file
    name when an icon is added to it, and the service worker serves fonts
    from its cache first (stale-while-revalidate), so without this the new
    icon was a blank square for the first view after a deploy."""
    digest = hashlib.sha256((ROOT / css_url).read_bytes()).hexdigest()[:10]
    return f"{css_url}?v={digest}"


def swap_font_sources(css: str) -> str:
    for marker, pattern, replacement in FONT_SUBSTITUTIONS:
        if (ROOT / marker).exists():
            src = re.sub(r"url\(([^)?]+)\)", lambda u: f"url({fingerprint(u.group(1))})", replacement)
            css = pattern.sub(lambda m: m.group(1) + src, css)
    return css


# Vendor sheets whose classes are largely runtime-generated by their JS —
# static usage analysis cannot see them, so they ship unpruned (~5KB).
NO_PRUNE = {"css/magnific-popup.css"}


def build(usage=None) -> str:
    source = SOURCE.read_text(encoding="utf-8")
    imports = IMPORT_RE.findall(source)
    body = IMPORT_RE.sub("", source)
    usage = usage or collect_usage()

    parts = []
    for imp in imports:
        f = ROOT / imp
        css = CHARSET_RE.sub("", f.read_text(encoding="utf-8"))
        css = rewrite_urls(css, f)
        css = minify(css)
        if imp not in NO_PRUNE:
            css = prune(css, usage)
        parts.append(swap_font_sources(css))
    parts.append(prune(minify(CHARSET_RE.sub("", body)), usage))

    # Keyframes last, across every part at once: an animation declared in
    # style.css may run keyframes that animate.css defines.
    keep = keyframe_references("\n".join(parts)) | usage.words
    parts = [prune_keyframes(p, keep) for p in parts]
    return "\n".join([BANNER, *parts]) + "\n"


ICON_CLASS_RES = [
    (r'\.(fa-[\w-]+):+before\s*\{\s*content:', ROOT / "css" / "font-awesome.min.css", "FontAwesome"),
    (r'\.(ti-[\w-]+):+before\s*\{\s*content:', ROOT / "css" / "default-assets" / "themify-icons.css", "themify"),
    (r'\.((?:icon|arrow|social)_[\w-]+):+before\s*\{\s*content:', ROOT / "css" / "style.css", "ElegantIcons"),
]


def stale_icon_subsets(usage):
    """Icon classes used by tracked content but missing from the subset
    fonts (per fonts/subset-manifest.json). Empty list = all good."""
    manifest_path = ROOT / "fonts" / "subset-manifest.json"
    if not manifest_path.exists():
        return []
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    missing = []
    for pattern, css_file, name in ICON_CLASS_RES:
        defined = set(re.findall(pattern, css_file.read_text(encoding="utf-8")))
        covered = set(manifest.get(name, []))
        missing += sorted(usage.used(defined) - covered)
    return missing


def main(argv=None):
    parser = sitelib.arg_parser(__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if style.min.css differs from a fresh build; write nothing")
    args = parser.parse_args(argv)

    usage = collect_usage()
    output = build(usage)
    missing_icons = stale_icon_subsets(usage)
    if missing_icons:
        print("icon font subsets are stale: these used icons are not in "
              f"fonts/subset-manifest.json: {missing_icons}")
        print("Run: python .github/scripts/subset_icon_fonts.py "
              "then rebuild the min CSS.")
        return 1
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != output:
            print("style.min.css is stale. Run: python .github/scripts/minify_css.py")
            return 1
        print("style.min.css is up to date.")
        return 0
    TARGET.write_text(output, encoding="utf-8", newline="\n")
    source = SOURCE.read_text(encoding="utf-8")
    print(f"Wrote {TARGET.name}: {len(output):,} bytes "
          f"(source {SOURCE.stat().st_size:,} + {len(IMPORT_RE.findall(source))} imports inlined)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
